### ISSUE TITLE
Error: Pyperclip could not find a copy/paste mechanism for your system.

### ISSUE THREAD

**Issue by donatid** [RaihanStark/instalivecli#1]
Hi,

I found the following error when tried to run this script:

Let's do it!
You'r logged in
Traceback (most recent call last):
  File "live_broadcast.py", line 5, in <module>
    live.start()
  File "/root/instalivecli/InstaLiveCLI/InstaLiveCLI.py", line 428, in start
    if self.create_broadcast():
  File "/root/instalivecli/InstaLiveCLI/InstaLiveCLI.py", line 617, in create_broadcast
    pyperclip.copy(self.stream_key)
  File "/usr/local/lib/python3.8/site-packages/pyperclip/__init__.py", line 618, in lazy_load_stub_copy
    return copy(text)
  File "/usr/local/lib/python3.8/site-packages/pyperclip/__init__.py", line 303, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 

I have same problem on Ubuntu Bionic 64bit and CentOS 8 64bit with python3.8 and no X11 
I also already installed xsel and xclip but didn't solve this issue.

Do you have any suggestions?

Thank you

**Comment by RaihanStark** [comment]
Hi donatid,

Thanks for reporting the bug! I hope that commit solves your problem.

Thank you
